steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/kidsndogs/train_model', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/kidsndogs/train_model']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/kidsndogs/predict_model', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/kidsndogs/predict_model']