name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # This step checks out your repository under $GITHUB_WORKSPACE, so the job can access it.

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      # This step sets up a Python 3.8 environment.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # This step upgrades pip and installs your project's dependencies.
      # 'requirements.txt' should list your project's dependencies,
      # and 'requirements_tests.txt' should list dependencies specific to testing.
      
    - uses: iterative/setup-dvc@v1
    
    - name: Get data
      run: dvc pull

    - name: Download Best Model
      run: |
        python download_public.py
      # This step downloads the best model from the specified URL into the knd/models directory.

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v

    - name: Run Profiler
      run: python ./knd/predict_model.py ./tests/03-01-08-01-02-02-03.wav ./models/best_model.ckpt
      # This step runs the profiler on the script and outputs the result to profile_output.
    
    - name: Upload profiling output
      uses: actions/upload-artifact@v2
      with:
        name: profiling-output
        path: ./log/profile_output.json
      # This step uploads the profiling output as an artifact of the workflow run.
